on:
  push:
    branches:
      - master

env:
  APP_NAME: ${APP_NAME}
  IMAGE_TAG: ${IMAGE_TAG}
  KUBERNETES_NAMESPACE: m324-team4
  BASE_URL: ngawang.m324.hackerman.ch

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master

      - uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_TAG }}

      - name: Check and Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
        id: install

      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Replace and Apply Kubernetes Manifests
        uses: swdotcom/update-and-apply-kubernetes-configs@v1
        with:
          kubernetes-config-file-paths: |
            ./kubernetes-manifest/00_namespace.yml
            ./kubernetes-manifest/01_deployment.yml
            ./kubernetes-manifest/02_service.yml
            ./kubernetes-manifest/03_ingress.yml
            ./kubernetes-manifest/04_ingress_example.yml

          replacement-method: defined
